theme: jekyll-theme-cayman
title: Martin Stejskal
description: Martin Stejskal - Visionär, der es liebt auf der Welle der Bleeding-Edge-Technologien zu surfen und dabei den Wind der Innovation zu spüren.